@extends('adminlayout.layout.header_footer')
    @section('content')
    <style>
        .wrapper{
            page-break-after: always;
        }
        body{
            margin:0px;
            padding:0px;
            box-sizing:border-box;
        }
        p{
            font-size:13px
        }
        
       
        .boldtext{
            font-weight:bold;
        }
        .row{
            margin:5px
        }
        .stamp{
            height:100px;
            width:100px;
            background-image:url('images/clients/stampic.jpeg');
            background-size:100% 100%;
            background-position:center;
            margin-left:10px;
           
        }
        .letterheader{
            height:200px;
            background-image:url('images/clients/letterheader.jpeg');
            background-size:100% 100%;
            background-position:center;
            
        }
        .letterfooter{
            height:130px;
            background-image:url('images/clients/letterfooter.jpeg');
            background-size:100% 100%;
            background-position:center;
         
          
        }
        td{
            border:1px solid black;
            padding:10px
        }
    </style>
    <div class="row">
        <div class="col-lg-9">
            <h3>
            Inspection Report
            </h3>
        </div>
        <div class="col-lg-3">
            
            <a href="gen_inspect_report" class="btn btn-primary">Download as PDF</a>
            
        </div>
    </div>
    <hr>
    @foreach($record as $d)
    <div id="divtoprint" class="container-fluid" style="background-color:white">
    <div class="wrapper">
    <div class="row">
        <div class="col-lg-12 letterheader"></div>
    </div>
    <main>
                <table style="border:1px solid black;width:100%">
                    <tr>
                        <td><b>To</b></td>
                        <td>{{$d->supervisorname}}</td>
                        <td><b>Company Name</b></td>
                        <td>{{$d->companyname}}</td>
                    </tr>
                    <tr>
                        <td><b>Date</b></td>
                        <td>{{$d->reportsent_date}}</td>
                        <td><b>Report Generated By</b></td>
                        <td>{{$d->generated_by}}</td>
                    </tr>
                </table>
                <hr>
                <p><b>Subject : </b>{{$d->subject}}</p>
                <hr>

                <div>
                <b>Dear Sir / Madam, </b>
                    <hr>
                    <p>
                    We, the dedicated team of S.S. Elevators, would like to draw your attention to a number of critical issues that have been identified in your project. These issues are of significant concern as they may impact the overall safety, efficiency, and performance of your system. We believe that addressing these matters promptly is essential for ensuring the optimal functionality and longevity of the project. Therefore, we have documented each issue in detail to provide you with a comprehensive understanding of the challenges at hand and the necessary steps required to resolve them.

                    </p>
                    <p>
                        We have been observing <b>{{$d->no_of_issues}} errors</b> since, <b>{{$d->errorobserved_date}}</b>
                    </p>
                    <p>
                    Our dedicated team has been diligently working to identify and address the various issues that have arisen in your project. We believe it is important to keep you informed about the nature and specifics of these issues to ensure transparency and foster a collaborative approach towards resolving them. Below, we have provided a detailed list of the issues we have encountered, along with relevant observations and insights.

                    </p>
                    <hr>
                    <ol>
                        @php
                        $iss = explode(',', $d->issues);
                        @endphp
                        @foreach($iss as $issue)
                        <li>{{$issue}}</li>
                        @endforeach
                    </ol>

                </div>
               
                <div class="page-break"></div>
                <hr>
                <b>Additional Details</b>
                <p>{{$d->additionaldetails}}</p>
                <hr>
                <div>
                    <p>
                    We have meticulously listed all these issues for you with the utmost care and attention because your safety and satisfaction are our highest priorities. Ensuring that you are fully aware of the challenges we have identified allows us to work together more effectively towards resolving them. By prioritizing these concerns, we aim to enhance the reliability and performance of your system, thereby guaranteeing your peace of mind and overall satisfaction with our services. Our commitment to your safety and satisfaction drives us to maintain the highest standards of excellence in addressing and rectifying these issues.

                    </p>
                    <p>We would like to request you to please carefully read all these issues and <b>grant us the go-ahead</b> to fix these issues, we would be needing yours and your staff's co-operation till the complete resolution of the errors.</p>
                    <hr>
                    <p>We would also like to notify you that the complete duration for resolving these errors including the observation period will be <b> {{$d->duration_to_work}} {{$d->unit}}</b> after the date of allowance / approval from your side.</p>
                </div>
                <hr>
                <p>Regards,</p>
                <b>Asad Uddin Qureshi</b>
                <p>C.E.O</p>
                <p>S.S. Elevators</p>

                <div class="stamp"></div>
            </main>
    </div>
    </div>
    
    @endforeach
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js" integrity="sha512-GsLlZN/3F2ErC5ifS5QtgpiJtWd43JWSuIgh7mbzZ8zBps+dvLusV+eNQATqgA/HdeKFVgA5v3S/cIrLF7QnIg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
    function convert_to_pdf(){
      var divoprint = document.getElementById('convert')
      html2pdf().from(divtoprint).save();
    }
  </script>
    @endsection
  