@extends('adminlayout.layout.header_footer')
@section('content')
<h3>Generate Inspection Report</h3>
<br>
<p>Kindly , fill in all the required details to generate your report</p>

<p>This report is being generated by <b>{{session('admin')}}</b></p>
<hr>
<form action="generate_ins" method="post">
    @csrf
    <div class="row">
        <div class="col-lg-6 mt-3">
        <b>Enter manager / Supervisor name</b>
        <input type="text" class="form-control" required name="managername"
        >
        </div>
        <div class="col-lg-6 mt-3">
        <b>Enter company name</b>
        <input type="text" class="form-control" required name="companyname">
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 mt-3">
        <b>Enter subject of your report</b>
        <input type="text" class="form-control" required name="subject"
        >
        </div>
        <div class="col-lg-4 mt-3">
        <b>Enter duration </b>
        <input type="number" class="form-control" required name="duration">
        </div>
        <div class="col-lg-4 mt-3">
        <b>Enter duration </b>
        <select name="unitlist" id="" class="form-control">
            <option value="" selected disabled>Select Days / Weeks / Months</option>
            <option value="days">Days</option>
            <option value="weeks">Weeks</option>
            <option value="months">Months</option>
        </select>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6 mt-3">
        <b>Error was first observed on</b>
        <input type="date" class="form-control" name="observed_date"
        required>
        </div>
        <div class="col-lg-6 mt-3">
        <b>Date on which report will be sent</b>
        <input type="date" class="form-control" name="sent_date" required>
        </div>
    </div>
    
        <div class="row">
            <div class="col-lg-8 mt-3">
                <b>Enter number of issues / errors</b>
                <input type="number" class="form-control" name="totalissues" id="no_of_issues">
                
            </div>
            <div class="col-lg-4 mt-3">
                <br>
               <button class="btn btn-success" id="btngenerate" type="button" onclick="generate()">Generate Fields</button>
                <script>
                    function generate(){
                        var inp1 = document.getElementById('no_of_issues');
                        var inp = document.getElementById('no_of_issues').value;
                        var btngen = document.getElementById('btngenerate')
                       
                        var divtoembed = document.getElementById('mydivtoprint');
                        if(inp > 0){
                            
                             btngen.innerText="Add another field"
                            for(var i = 1 ; i <= inp ; i++){
                            var inputdetails = document.createElement('input');
                            inputdetails.type="text"
                            inputdetails.name ="issues[]"
                            inputdetails.required=true
                            inputdetails.className="form-control mt-2"
                            inputdetails.placeholder="Describe issue here"
                            divtoembed.appendChild(inputdetails)
                            
                        }
                       
                        }
                        else{
                             btngen.innerText="Generate Fields"
                            alert('No valid number of issues given')
                        }
                         
                    }
                </script>
            </div>

        </div>
        <div class="row">
            <div class="col-lg-12 mt-3" id="mydivtoprint">

            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 mt-3">
                <b>Any Additional Detail ? <span style="color:grey">(Optional)</span></b>
                <textarea name="additional" id="" class="form-control"></textarea>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 mt-3">
                <button class="btn btn-primary w-100" type="submit">
                    Generate Inspection Report
                </button>
            </div>
        </div>
    </div>
</form>
@endsection